# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-archiver" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "eacf673995b6c3529acad419bc5a6036ae54060e3c93fbef08566830985bbbfd"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "73dd8a50b8d4ee90edd84351cc73d63cc1fa5f985ed1413eb281032fe35c9c5e"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "51f93e401f75a4d8c53875b5d4480bdac36f86bfc81c4f4bcf2e735dd55c420a"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "06d7e26e761f81cc0b761cc661d931020606b460e0d8a268df13a17e8a4bafbe"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_linux_arm64.zip"
    end
  end

  name "agent-archiver"
  desc "export sites to markdown"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-archiver"

  # No zap stanza required

end
