# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-archiver" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_darwin_amd64.zip"
      sha256 "f8231eee7b4a488b504d24abafcafaf177611c2f138f392bd5359b94d8cee5ca"
    end
    on_arm do
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_darwin_arm64.zip"
      sha256 "abb2949cdbf22c03188372b50023782b95ce021d0b5b2bef0abb2ed6b2887a39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_linux_amd64.zip"
      sha256 "aa4e6259b8e9a28bbeea110419e8f7f72fd7bd2da44d275fb966103db66f253f"
    end
    on_arm do
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_linux_arm64.zip"
      sha256 "2aab4290413af2f24fa94ff4b976fcc5344d8e2f6bc2f1720819e2313b87dd50"
    end
  end

  name "agent-archiver"
  desc "export sites to markdown"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-archiver"

  # No zap stanza required

end
