# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-archiver" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "fc0222f510bbd4e247519a29ba82fa5a746a804428668a7b6dbeeeeaf35a8130"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "802429c93c656ad4a23001444d84e25a17e5b4b9c7fd58f03de76e65bd867434"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ff628bccc98017ab9e6d68710b081d12be67df295894a2906bc3c9af54f1e6a"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "cead81ed6fd1f9d6f7787878eeebd70273494a8b0cda7ab8b51e9f7daacf8a0a"
      url "https://github.com/lingrino/agent-archiver/releases/download/v#{version}/agent-archiver_#{version}_linux_arm64.zip"
    end
  end

  name "agent-archiver"
  desc "export sites to markdown"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-archiver"

  # No zap stanza required

end
