# This file was generated by GoReleaser. DO NOT EDIT.
cask "glen" do
  name "glen"
  desc "A CLI to gather GitLab project and group variables."
  homepage "https://lingrino.com/"
  version "1.9.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glen"

  on_macos do
    on_intel do
      url "https://github.com/lingrino/glen/releases/download/v#{version}/glen_#{version}_darwin_amd64.zip"
      sha256 "712103da0b7dad816c7d27858bbdfa2026706acba8a9d4ae54c2b1894ccab5ab"
    end
    on_arm do
      url "https://github.com/lingrino/glen/releases/download/v#{version}/glen_#{version}_darwin_arm64.zip"
      sha256 "02be7563b0693c514fa33afd04e11d257eae95e0f714f764e454aa2865ddb3c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lingrino/glen/releases/download/v#{version}/glen_#{version}_linux_amd64.zip"
      sha256 "ed47572be967e0fa136e81f5ce3a85127896442f41af0c329e56f4dfd0a8b430"
    end
    on_arm do
      url "https://github.com/lingrino/glen/releases/download/v#{version}/glen_#{version}_linux_arm64.zip"
      sha256 "48544ef064b17ba2c40d07573dde119860f123691cc9111147895f5925dde2b7"
    end
  end

  # No zap stanza required
end
