# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaku" do
  name "vaku"
  desc "CLI that extends the official Vault client."
  homepage "https://vaku.dev/"
  version "2.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaku"

  on_macos do
    on_intel do
      url "https://github.com/lingrino/vaku/releases/download/v#{version}/vaku_#{version}_darwin_amd64.zip"
      sha256 "c5ed9a415094ada415079b150878f06966f40d8aa7af0cbb931779c1bec9b5fe"
    end
    on_arm do
      url "https://github.com/lingrino/vaku/releases/download/v#{version}/vaku_#{version}_darwin_arm64.zip"
      sha256 "b3a869cc88976e9e3a444f583f7cb0a2c073805278d4a2aba5133bf41b82cd53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lingrino/vaku/releases/download/v#{version}/vaku_#{version}_linux_amd64.zip"
      sha256 "0004263dabb656f7f303375199a76974c73e362bcaa418b4232609f040da7a9d"
    end
    on_arm do
      url "https://github.com/lingrino/vaku/releases/download/v#{version}/vaku_#{version}_linux_arm64.zip"
      sha256 "fd4798eafa654b07ae55e16fdb70d6cb035b9832835b1c9bf160e25ee14df54b"
    end
  end

  # No zap stanza required
end
