# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glen < Formula
  desc "A CLI to gather GitLab project and group variables."
  homepage "https://lingrino.com/"
  version "1.8.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lingrino/glen/releases/download/v1.8.1/glen_1.8.1_darwin_arm64.zip"
      sha256 "9a5f408000d1afb117b141b2bbf52bc5c2e018b1e71936f87a188390bfa17140"

      def install
        bin.install "glen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/glen/releases/download/v1.8.1/glen_1.8.1_darwin_amd64.zip"
      sha256 "06e8475fe26b7f68e6d2fb95b84b5390dc7315f6c5170025e6ec58d88ebecb97"

      def install
        bin.install "glen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lingrino/glen/releases/download/v1.8.1/glen_1.8.1_linux_arm64.zip"
      sha256 "ab708da95aa70d42326066091f2c8a642438e1877bf88839f79d0921e1e753bc"

      def install
        bin.install "glen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/glen/releases/download/v1.8.1/glen_1.8.1_linux_amd64.zip"
      sha256 "c24f7acb2c3ba4471ad092dd66c839a7695d3a9c9dacf938d6f8cadece985442"

      def install
        bin.install "glen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lingrino/glen/releases/download/v1.8.1/glen_1.8.1_linux_armv6.zip"
      sha256 "2534456405fa2a7e641223eba7d3e430564b7968429f5dc94d9c7827561c7b81"

      def install
        bin.install "glen"
      end
    end
  end

  test do
    system "#{bin}/glen version"
  end
end
