# This file was generated by GoReleaser. DO NOT EDIT.
class Hoo < Formula
  desc "A tool for knowing who you are on remote services"
  homepage "https://hoo.dev/"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lingrino/hoo/releases/download/v0.0.1/hoo_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "3efd6a879dcdefdf05b9ca954667a68a35954a496e458f36a722b79ddb5e8180"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/hoo/releases/download/v0.0.1/hoo_0.0.1_Linux_x86_64.tar.gz"
      sha256 "f97ba7472110257bbbd3c3a26a68daa2526733cffeb0910d26c4257a3199a79a"
    end
  end
  
  depends_on "vault"

  def install
    bin.install "hoo"
  end

  test do
    system "#{bin}/hoo version"
  end
end
