# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaku < Formula
  desc "CLI that extends the official Vault client."
  homepage "https://vaku.dev/"
  version "2.6.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lingrino/vaku/releases/download/v2.6.3/vaku_2.6.3_darwin_arm64.zip"
      sha256 "89444083efecec92068c8aece500493fe7eae3bbbe3bcc61f8fefb933f143e70"

      def install
        bin.install "vaku"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/vaku/releases/download/v2.6.3/vaku_2.6.3_darwin_amd64.zip"
      sha256 "d1f4ad78e9837222c909c8d5713bfcb8246486f361cd2a5fd3165b5d64374cce"

      def install
        bin.install "vaku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lingrino/vaku/releases/download/v2.6.3/vaku_2.6.3_linux_armv6.zip"
      sha256 "ae6188580e6e7dce9d512d31cd0dda2b8338e8a173c48f0089c71f4249d77da9"

      def install
        bin.install "vaku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lingrino/vaku/releases/download/v2.6.3/vaku_2.6.3_linux_arm64.zip"
      sha256 "76ae5d3bf140a7c51396a1066ea862a16aefad3c011b1d3029b06cf60e0e1fc2"

      def install
        bin.install "vaku"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/vaku/releases/download/v2.6.3/vaku_2.6.3_linux_amd64.zip"
      sha256 "5ce1f4425e248cd923b456c77b5b28eefddece39ac603da0f7f107cddb4885c7"

      def install
        bin.install "vaku"
      end
    end
  end

  test do
    system "#{bin}/vaku version"
  end
end
