# This file was generated by GoReleaser. DO NOT EDIT.
class Vaku < Formula
  desc "CLI that extends the official Vault client."
  homepage "https://vaku.dev/"
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lingrino/vaku/releases/download/v2.0.0/vaku_2.0.0_mac_x86_64.zip"
    sha256 "4382b274764796672f4979df3f2ba99bd984d01ac088c9a26f029dfc7c670985"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/vaku/releases/download/v2.0.0/vaku_2.0.0_linux_x86_64.zip"
      sha256 "5ef0cb81b94c7287ce65314c5a687c41bacc33173b235e311a050076fe48da4e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lingrino/vaku/releases/download/v2.0.0/vaku_2.0.0_linux_arm64.zip"
        sha256 "4384055af5da54c65195033cd03092440ca1291a2a8cd49df033cebb0bbf966f"
      else
        url "https://github.com/lingrino/vaku/releases/download/v2.0.0/vaku_2.0.0_linux_armv6.zip"
        sha256 "73e0935afdddad4da880c63640640e535d3bb97ec2fcd5b80a15de593302ce2a"
      end
    end
  end

  def install
    bin.install "vaku"
  end

  test do
    system "#{bin}/vaku version"
  end
end
