# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaku < Formula
  desc "CLI that extends the official Vault client."
  homepage "https://vaku.dev/"
  version "2.3.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lingrino/vaku/releases/download/v2.3.0/vaku_2.3.0_mac_x86_64.zip"
    sha256 "cdfc549a229623f5527f7aa8a1702855f37f8bf857f95d9ab2f30559f85d903f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lingrino/vaku/releases/download/v2.3.0/vaku_2.3.0_mac_arm64.zip"
    sha256 "d631530df9066009960c5543a3a2214142d2b5cd1aec635e8574235d5e212184"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lingrino/vaku/releases/download/v2.3.0/vaku_2.3.0_linux_x86_64.zip"
    sha256 "2965430abff0d8faefbd8f5fcf25e48ed7746b21c9f4e0248b340f93208f81d5"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lingrino/vaku/releases/download/v2.3.0/vaku_2.3.0_linux_armv6.zip"
    sha256 "eb4d619c65c2acf63f2f833424db948c47350da87f9aef55c7ee2c444522847d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lingrino/vaku/releases/download/v2.3.0/vaku_2.3.0_linux_arm64.zip"
    sha256 "1d7d3b77e51e6ccef4eb5640cf1361a159b4cd3285e2b2d130d2e245acf100c7"
  end

  def install
    bin.install "vaku"
  end

  test do
    system "#{bin}/vaku version"
  end
end
