# This file was generated by GoReleaser. DO NOT EDIT.
class glen < Formula
  desc "A CLI to gather GitLab project and group variables"
  homepage "https://lingrino.com/"
  version "1.1.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lingrino/glen/releases/download/v1.1.6/glen_1.1.6_mac_x86_64.zip"
    sha256 "72edf99fbcb8c434fc24201c291e255c6fc59199fd5e744b3c2cb6de64e5bcfb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lingrino/glen/releases/download/v1.1.6/glen_1.1.6_linux_x86_64.zip"
      sha256 "5593f493428d05418bb3c7b02434e4a23da3059e91cba2466b3ec8788f801a8d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lingrino/glen/releases/download/v1.1.6/glen_1.1.6_linux_arm64.zip"
        sha256 "1ce1782b44361c136d07c0ddb92f861a0c5cf75172e36bcc53620010e6172dc8"
      else
        url "https://github.com/lingrino/glen/releases/download/v1.1.6/glen_1.1.6_linux_armv6.zip"
        sha256 "fce4945a9c1434500817751ac05036506f3fb2484a1cd976557795187bf991f0"
      end
    end
  end

  def install
    bin.install "glen"
  end

  test do
    system "#{bin}/glen version"
  end
end
